.PHONY: clean
clean:
	rm a.exe

.PHONY: build
build:
	g++ -Wall hlp.cpp -lcrypto

.PHONY: run
run:
	./a.exe

.PHONY: start
start:
	rm a.exe
	g++ -Wall hlp.cpp -lcrypto
	./a.exe

.PHONY: show
show:
	cat /home/Алина/users.txt
